### ISSUE TITLE
Implement on.exit for all functions

### ISSUE THREAD

**Issue by arg0naut91** [arg0naut91/chronshape#26]
Which should also enable printing output to console

**Comment by arg0naut91** [comment]
@Patrikios I applied the `on.exit` part you implemented for `collapse_ranges `to other functions; feel free to adjust if you see the need.

**Comment by Patrikios** [comment]
Nice! 
Thanks for ameliorations and for adding me to the authors list. I appreciate it. 
Still have to test my build on fedora later today, it must have been the flags as u mentioned earlier. 

I think generally, the function can be a bit stricter for user inputs. Do that less can go wrong. Then I will most probably think of new feature or two. 

VG
Patrik

**Comment by arg0naut91** [comment]
Great, thanks! I think it'd be great if we would open an issue for any of the improvements we're working on, and then refer to them in commits (with the #), may enable better tracking of changes.

In the meantime I think I'll submit version 0.1.4 to CRAN soon - due to discovered errors - and then we do 0.1.5 with new adjustments / additions. I''ve also been testing GitHub Actions which seem to be the way to go today in terms of package checks upon committing.

**Comment by Patrikios** [comment]
Yes, sure, will do, good idea!
